language: cpp

compiler:
- gcc
- clang

addons:
apt:
 sources:
  - george-edison55-precise-backports
 packages:
  - cmake
  - cmake-data
  - clang-3.7
  - g++-7

script:
- cd hello_world_application
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install  -DBUILD_TESTS=ON
- cmake --build _build
- cmake --build _build --target hello_world
- cmake --build _build --target test -- ARGS=--verbose
- ./_build/hello_world
- echo "Hello world application testing is done"
- cd ..
- cd solver_application
- cmake -H. -B_build
- cmake --build _build
- cmake --build _build --target solver
- echo "Solver application testing is done"
